{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/IncidentReporting/Pages/PA85839U10_SafetyIncidents/SafetyIncidents_CreateIncidentPhotos.page",
    "_Type": "Action.Type.Navigation"
}